ALTER TABLE tarefa
  MODIFY COLUMN data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN data_atualizacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
   
ALTER TABLE usuario
  ADD COLUMN data_criacao DATETIME DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN data_atualizacao DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP


  