ALTER TABLE tarefa
  ADD COLUMN autor bigint(30) NOT NULL,
  ADD COLUMN titulo VARCHAR(255) NOT NULL,
  ADD COLUMN data_inicio DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  ADD COLUMN data_final DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  ADD COLUMN prioridade VARCHAR(255) NOT NULL,
  
  ADD CONSTRAINT fk_autor_usuario_id FOREIGN KEY (autor) REFERENCES usuario (id);


  